### ISSUE TITLE
PROBLEM when creating seq2seq model

### ISSUE THREAD

**Issue by sherlick** [nfmcclure/tensorflow_cookbook#112]
Chapter 9, Creating Sequence-to-Sequence Models
When running the code, I get this problem saying: ## TypeError: can't pickle _thread.lock objects
details:
Traceback (most recent call last):

  File "<ipython-input-1-048e5362043a>", line 1, in <module>
    runfile('C:/Users/lc/.spyder-py3/practice/11.29/1_.py', wdir='C:/Users/lc/.spyder-py3/practice/11.29')

  File "X:\Anaconda3\envs\py36\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "X:\Anaconda3\envs\py36\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/lc/.spyder-py3/practice/11.29/1_.py", line 213, in <module>
    forward_only=False)

  File "C:/Users/lc/.spyder-py3/practice/11.29/1_.py", line 195, in translation_model
    forward_only=forward_only)

  File "C:\Users\lc\.spyder-py3\practice\11.29\seq2seq_model.py", line 69, in __init__
    softmax_loss_function=loss_fun)

  File "X:\Anaconda3\envs\py36\lib\site-packages\tensorflow\contrib\legacy_seq2seq\python\ops\seq2seq.py", line 1209, in model_with_buckets
    decoder_inputs[:bucket[1]])

  File "C:\Users\lc\.spyder-py3\practice\11.29\seq2seq_model.py", line 68, in <lambda>
    self.target_weights, xy_buckets, lambda x, y: decode_wrapper(x, y, False),

  File "C:\Users\lc\.spyder-py3\practice\11.29\seq2seq_model.py", line 37, in decode_wrapper
    dtype=tf.float32)

  File "X:\Anaconda3\envs\py36\lib\site-packages\tensorflow\contrib\legacy_seq2seq\python\ops\seq2seq.py", line 851, in embedding_attention_seq2seq
    encoder_cell = copy.deepcopy(cell)

  File "X:\Anaconda3\envs\py36\lib\copy.py", line 161, in deepcopy
    y = copier(memo)

  File "X:\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\layers\base.py", line 655, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))

  File "X:\Anaconda3\envs\py36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)

  File "X:\Anaconda3\envs\py36\lib\copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))

  File "X:\Anaconda3\envs\py36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)

  File "X:\Anaconda3\envs\py36\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)

  File "X:\Anaconda3\envs\py36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)

  File "X:\Anaconda3\envs\py36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)

  File "X:\Anaconda3\envs\py36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)

  File "X:\Anaconda3\envs\py36\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)

  File "X:\Anaconda3\envs\py36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)

  File "X:\Anaconda3\envs\py36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)

  File "X:\Anaconda3\envs\py36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)

  File "X:\Anaconda3\envs\py36\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)

  File "X:\Anaconda3\envs\py36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)

  File "X:\Anaconda3\envs\py36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)

  File "X:\Anaconda3\envs\py36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)

  File "X:\Anaconda3\envs\py36\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)

  File "X:\Anaconda3\envs\py36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)

  File "X:\Anaconda3\envs\py36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)

  File "X:\Anaconda3\envs\py36\lib\copy.py", line 169, in deepcopy
    rv = reductor(4)

TypeError: can't pickle _thread.lock objects

**Comment by maxim5** [comment]
See [this issue and a workaround](https://github.com/tensorflow/tensorflow/issues/11157#issuecomment-353725791)

**Comment by nfmcclure** [comment]
I think there is now a solution in the current TensorFlow version. I'll be updating the code/notebooks over the next few months. Look for a fix soon.

**Comment by nfmcclure** [comment]
This should be fixed now. Try the new code. If it doesn't work, feel free to re-open and also post your Python version, pickle version, and TensorFlow version, along with what operating system you are using.
